COUNTRY_EXTENSIONS = [
[False, "Afghanistan", ".af"],
[False, "Åland", ".ax"],
[False, "Albania", ".al"],
[False, "Algeria", ".dz "],
[False, "American Samoa", ".as"],
[False, "Andorra", ".ad"],
[False, "Angola", ".ao"],
[False, "Anguilla", ".ai"],
[False, "Antarctica", ".aq"],
[False, "Antigua and Barbuda", ".ag"],
[False, "Argentina", ".ar"],
[False, "Armenia", ".am"],
[True, "Aruba", ".aw "],
[False, "Ascension Island", ".ac"],
[False, "Australia", ".au"],
[False, "Austria", ".at"],
[False, "Azerbaijan", ".az"],
[False, "Bahamas", ".bs"],
[False, "Bahrain", ".bh"],
[False, "Bangladesh", ".bd"],
[False, "Barbados", ".bb"],
[False, "Basque Country", ".eus"],
[False, "Belarus", ".by"],
[False, "Belgium", ".be"],
[False, "Belize", ".bz"],
[False, "Benin", ".bj"],
[False, "Bermuda", ".bm"],
[False, "Bhutan", ".bt"],
[False, "Bolivia", ".bo"],
[True, "Bonaire", ".bq "],
[False, "Bosnia and Herzegovina", ".ba"],
[False, "Botswana", ".bw"],
[False, "Bouvet Island", ".bv"],
[False, "Brazil", ".br"],
[False, "British Indian Ocean Territory", ".io"],
[False, "British Virgin Islands", ".vg"],
[False, "Brunei", ".bn"],
[False, "Bulgaria", ".bg"],
[False, "Burkina Faso", ".bf"],
[False, "Burma"],
[False, "Burundi", ".bi"],
[False, "Cambodia", ".kh"],
[False, "Cameroon", ".cm"],
[False, "Canada", ".ca"],
[False, "Cape Verde"],
[False, "Catalonia", ".cat"],
[False, "Cayman Islands", ".ky"],
[False, "Central African Republic", ".cf"],
[False, "Chad", ".td"],
[False, "Chile", ".cl"],
[False, "China", " People’s Republic of,.cn"],
[False, "Christmas Island", ".cx"],
[False, "Cocos Islands", ".cc"],
[False, "Colombia", ".co"],
[False, "Comoros", ".km"],
[False, "Congo", " Democratic Republic of the,.cd"],
[False, "Congo", " Republic of the,.cg"],
[False, "Cook Islands", ".ck"],
[False, "Costa Rica", ".cr"],
[False, "Côte d’Ivoire", ".ci"],
[False, "Croatia", ".hr"],
[False, "Cuba", ".cu"],
[True, "Curaçao", ".cw"],
[False, "Cyprus", ".cy"],
[False, "Czechia (Czech Republic)", ".cz"],
[False, "Denmark", ".dk"],
[False, "Djibouti", ".dj"],
[False, "Dominica", ".dm"],
[False, "Dominican Republic", ".do"],
[False, "East Timor (Timor-Leste)", ".tl "],
[False, "East Timor (Old Version)", ".tp "],
[False, "Ecuador", ".ec"],
[False, "Egypt", ".eg"],
[False, "El Salvador", ".sv"],
[False, "Equatorial Guinea", ".gq"],
[False, "Eritrea", ".er"],
[False, "Estonia", ".ee"],
[False, "Ethiopia", ".et"],
[False, "European Union", ".eu"],
[False, "Falkland Islands", ".fk"],
[False, "Faeroe Islands", ".fo"],
[False, "Federated States of Micronesia", ".fm"],
[False, "Fiji", ".fj"],
[False, "Finland", ".fi"],
[False, "France", ".fr"],
[False, "French Guiana", ".gf"],
[False, "French Polynesia", ".pf"],
[False, "French Southern and Antarctic Lands", ".tf"],
[False, "Gabon", ".ga"],
[False, "Galicia", ".gal"],
[False, "Gambia", ".gm"],
[False, "Gaza Strip (Gaza)", ".ps"],
[False, "Georgia", ".ge"],
[False, "Germany", ".de"],
[False, "Ghana", ".gh"],
[False, "Gibraltar", ".gi"],
[False, "Greece", ".gr"],
[False, "Greenland", ".gl"],
[False, "Grenada", ".gd"],
[False, "Guadeloupe", ".gp"],
[False, "Guam", ".gu"],
[False, "Guatemala", ".gt"],
[False, "Guernsey", ".gg"],
[False, "Guinea", ".gn"],
[False, "Guinea-Bissau", ".gw"],
[False, "Guyana", ".gy"],
[False, "Haiti", ".ht"],
[False, "Heard Island and McDonald Islands", ".hm"],
[False, "Honduras", ".hn"],
[False, "Hong Kong", ".hk"],
[False, "Hungary", ".hu"],
[False, "Iceland", ".is"],
[False, "India", ".in"],
[False, "Indonesia", ".id"],
[False, "Iran", ".ir"],
[False, "Iraq", ".iq"],
[False, "Ireland", ".ie"],
[False, "Isle of Man", ".im"],
[False, "Israel", ".il"],
[False, "Italy", ".it"],
[False, "Jamaica", ".jm"],
[False, "Japan", ".jp"],
[False, "Jersey", ".je"],
[False, "Jordan", ".jo"],
[False, "Kazakhstan", ".kz"],
[False, "Kenya", ".ke"],
[False, "Kiribati", ".ki"],
[False, "Kosovo", "not assigned yet"],
[False, "Kuwait", ".kw"],
[False, "Kyrgyzstan", ".kg"],
[False, "Laos", ".la"],
[False, "Latvia", ".lv"],
[False, "Lebanon", ".lb"],
[False, "Lesotho", ".ls"],
[False, "Liberia", ".lr"],
[False, "Libya", ".ly"],
[False, "Liechtenstein", ".li"],
[False, "Lithuania", ".lt"],
[False, "Luxembourg", ".lu"],
[False, "Macau", ".mo"],
[False, "Macedonia", " North,.mk"],
[False, "Madagascar", ".mg"],
[False, "Malawi", ".mw"],
[False, "Malaysia", ".my"],
[False, "Maldives", ".mv"],
[False, "Mali", ".ml"],
[False, "Malta", ".mt"],
[False, "Marshall Islands", ".mh"],
[False, "Martinique", ".mq"],
[False, "Mauritania", ".mr"],
[False, "Mauritius", ".mu"],
[False, "Mayotte", ".yt"],
[False, "Mexico", ".mx"],
[False, "Moldova", ".md"],
[False, "Monaco", ".mc"],
[False, "Mongolia", ".mn"],
[False, "Montenegro", ".me"],
[False, "Montserrat", ".ms"],
[False, "Morocco", ".ma"],
[False, "Mozambique", ".mz"],
[False, "Myanmar", ".mm"],
[False, "Namibia", ".na"],
[False, "Nauru", ".nr"],
[False, "Nepal", ".np"],
[True, "Netherlands", ".nl"],
[False, "New Caledonia", ".nc"],
[False, "New Zealand", ".nz"],
[False, "Nicaragua", ".ni"],
[False, "Niger", ".ne"],
[False, "Nigeria", ".ng"],
[False, "Niue", ".nu"],
[False, "Norfolk Island", ".nf"],
[False, "North Cyprus", ".nc.tr"],
[False, "North Korea", ".kp"],
[False, "North Macedonia", ".mk"],
[False, "Northern Mariana Islands", ".mp"],
[False, "Norway", ".no"],
[False, "Oman", ".om"],
[False, "Pakistan", ".pk"],
[False, "Palau", ".pw"],
[False, "Palestine", ".ps"],
[False, "Panama", ".pa"],
[False, "Papua New Guinea", ".pg"],
[False, "Paraguay", ".py"],
[False, "Peru", ".pe"],
[False, "Philippines", ".ph"],
[False, "Pitcairn Islands", ".pn"],
[False, "Poland", ".pl"],
[False, "Portugal", ".pt"],
[False, "Puerto Rico", ".pr"],
[False, "Qatar", ".qa"],
[False, "Romania", ".ro"],
[False, "Russia", ".ru"],
[False, "Rwanda", ".rw"],
[False, "Réunion Island", ".re"],
[True, "Saba", ".bq"],
[True, "Saba 2", ".an "],
[False, "Saint Barthélemy", ".bl"],
[False, "Saint Helena", ".sh"],
[False, "Saint Kitts and Nevis", ".kn"],
[False, "Saint Lucia", ".lc"],
[False, "Saint Martin", ".mf"],
[False, "Saint-Pierre and Miquelon", ".pm"],
[False, "Saint Vincent and the Grenadines", ".vc"],
[False, "Samoa", ".ws"],
[False, "San Marino", ".sm"],
[False, "São Tomé and Príncipe", ".st"],
[False, "Saudi Arabia", ".sa"],
[False, "Senegal", ".sn"],
[False, "Serbia", ".rs"],
[False, "Seychelles", ".sc"],
[False, "Sierra Leone", ".sl"],
[False, "Singapore", ".sg"],
[True, "Sint Eustatius", ".bq"],
[True, "Sint Maarten", ".sx "],
[False, "Slovakia", ".sk"],
[False, "Slovenia", ".si"],
[False, "Solomon Islands", ".sb"],
[False, "Somalia", ".so"],
[False, "Somaliland", ".so"],
[False, "South Africa", ".za"],
[False, "South Georgia and the South Sandwich Islands", ".gs"],
[False, "South Korea", ".kr"],
[False, "South Sudan", ".ss"],
[False, "Spain", ".es"],
[False, "Sri Lanka", ".lk"],
[False, "Sudan", ".sd"],
[False, "Suriname", ".sr"],
[False, "Svalbard and Jan Mayen Islands", ".sj"],
[False, "Swaziland", ".sz"],
[False, "Sweden", ".se"],
[False, "Switzerland", ".ch"],
[False, "Syria", ".sy"],
[False, "Taiwan", ".tw"],
[False, "Tajikistan", ".tj"],
[False, "Tanzania", ".tz"],
[False, "Thailand", ".th"],
[False, "Togo", ".tg"],
[False, "Tokelau", ".tk"],
[False, "Tonga", ".to"],
[False, "Trinidad & Tobago", ".tt"],
[False, "Tunisia", ".tn"],
[False, "Turkey", ".tr"],
[False, "Turkmenistan", ".tm"],
[False, "Turks and Caicos Islands", ".tc"],
[False, "Tuvalu", ".tv"],
[False, "Uganda", ".ug"],
[False, "Ukraine", ".ua"],
[False, "United Arab Emirates (UAE)", ".ae"],
[False, "United Kingdom (UK)", ".uk"],
[False, "United States of America (USA)", ".us"],
[False, "United States Virgin Islands", ".vi"],
[False, "Uruguay", ".uy"],
[False, "Uzbekistan", ".uz"],
[False, "Vanuatu", ".vu"],
[False, "Vatican City", ".va"],
[False, "Venezuela", ".ve"],
[False, "Vietnam", ".vn"],
[False, "Wallis and Futuna", ".wf"],
[False, "Western Sahara", ".eh"],
[False, "Western Sahara 2", ".ma"],
[False, "Yemen", ".ye"],
[False, "Zambia", ".zm"],
[False, "Zimbabwe", ".zw"],
]
