general:
  working_directory:
    # depending if we are working under linux or windows you can set the base working directory
    Linux: /home/eelco/Projects/url_research
    Windows: /P/Projects/something_els
  cache_directory: cache
  output_directory: .
databases:
  addresses:
    # the initial data base with  the postal codes, addresses + kvk numberw
    # can contain multiple addresses for 1 kvk number
    file_name: final_kvkregister.csv
    keys:
      # the fields of the dataframe with the names below are referring to the corresponding column
      id: 0
      kvk_nummer: 1
      naam: 2
      straat: 3
      postcode: 4
      plaats: 5
  kvk_urls:
    # the csv file with urls per kvk number. One kvk number kan have multiple urls
    file_name: URL_kvk.csv
    keys:
      id: 0
      kvk_nummer: 1
      naam: 2
      url: 4
  kvk_selection_data_base:
    # the abr database which we use to make a selection of kvk numbers to read and process
    file_name: Cbspersoon_Regio47url.xlsx
    kvk_nummer: NhrVestKvkNummer
    kvk_sub_nummer: CpVestigingsNummer
    naam: CpHandelsnaam
    straat: CpVestStraat
    postcode: CPVestPostcode6
    plaats: CpVestWoonplaats
process_settings:
  n_url_count_threshold: 10000
  kvk_range_read:
    # give the first and last kvk number you want to  read from the input csv file to turn into
    # the sql file. If not given, all the number as read
    start: # 1000040
    stop:  # 1300000
  kvk_range_process:
    # once a kvk range has been written to sql, process the kvk numbers by checking the url
    # the range to process can be limitted here. If empty, all the kvk nunber are processed
    start:  # 24255704 # 24255434 # 24255704  # 34074187
    stop: # 34074187
  # max entries can be used to stop processing after a fixed number of kvk's
  maximum_entries: # 1
  threshold_distance: 5
  threshold_string_match: 0.5
  impose_url_for_kvk:
    # all the url that fail to give the correct match can here be impose
    # 24255704: apotheekdorpsweg.leef.nl
    8137415: www.tulpkeukens.nl