general:
  working_directory:
    # depending if we are working under linux or windows you can set the base working directory
    Linux: .
    Windows: /P/Projects/something_els
  cache_directory: cache
  store_html_to_cache: true
  internet_scraping: true
  search_urls: true
  max_cache_dir_size: 0  # altenatively: 1 GB or 1 MB 
  older_time: 1 s
  output_directory: .
  database_name: kvk_db
  database_type: postgres # sqlite
databases:
  addresses:
    # the initial data base with  the postal codes, addresses + kvk numberw
    # can contain multiple addresses for 1 kvk number
    file_name: final_kvkregister.csv
    keys:
      # the fields of the dataframe with the names below are referring to the corresponding column
      id: 0
      kvk_nummer: 1
      naam: 2
      straat: 3
      postcode: 4
      plaats: 5
  kvk_urls:
    # the csv file with urls per kvk number. One kvk number kan have multiple urls
    file_name: URL_kvk.csv
    keys:
      id: 0
      kvk_nummer: 1
      naam: 2
      url: 4
  kvk_selection_data_base:
    # the abr database which we use to make a selection of kvk numbers to read and process
    file_name: Cbspersoon_Regio47url.xlsx
    kvk_nummer: NhrVestKvkNummer
    kvk_sub_nummer: CpVestigingsNummer
    naam: CpHandelsnaam
    straat: CpVestStraat
    postcode: CPVestPostcode6
    plaats: CpVestWoonplaats
kvk_selection:
  apply_selection: true
  type: database  # or list if an explicit list is given
  database: kvk_selection_data_base  # reference to the database in 'databases'  to use
  kvk_list:
    - 11030894
    - 17204342
    - 24041199
    - 27011394
    - 30023353
    - 50225588
    - 52910563
    - 65865138
    - 66050537
    - 66312728
    - 68762291
process_settings:
  n_url_count_threshold: 10000
  kvk_range_read:
    # give the first and last kvk number you want to  read from the input csv file to turn into
    # the sql file. If not given, all the number as read
    start:  # 1000040
    stop:   # 1030000
  kvk_range_process:
    # once a kvk range has been written to sql, process the kvk numbers by checking the url
    # the range to process can be limitted here. If empty, all the kvk nunber are processed
    start: 8137415 # 4059949 # 8137415 # 1160461 # 22040224 # 24137476
    stop:   
  # max entries can be used to stop processing after a fixed number of kvk's
  maximum_entries: 1
  threshold_distance: 10
  threshold_string_match: 0.5
  impose_url_for_kvk:
    # all the url that fail to give the correct match can here be impose
    # 24255704: apotheekdorpsweg.leef.nl
    8137415: www.tulpkeukens.nl


